### ISSUE TITLE
Thought: default modules.root?

### ISSUE THREAD

**Issue by developit** [dherman/defense-of-dot-js#3]
Would it be reasonable to presume a default directory for `modules.root`?  All of my packages are currently structured and published in a format nearly identical to the "poly-packages" format described here, but none declare `modules.root`.  However, in all cases this value would simply be `src`.  Perhaps that would be enough?

**Comment by boopathi** [comment]
I'd prefer default `modules.root` would be nothing (the same as "./"), because there are many modules that don't have the `src` directory, and it's just a convention that many projects use `src` so as to keep tooling configuration easier, maybe. 

And it would be a pain for simple no folder structure (all files in `./` & naming main file as index.js, and here `module.js`) modules to rewrite that option as `modules.root: "./"` when they want to keep things simple without configuring all of the properties of package.json.

**Comment by developit** [comment]
For simple (non-poly) packages, `index.js` marked as main would already work.  These is more specific to poly-packages.

**Comment by caridy** [comment]
@developit `modules.root` is not specific for poly-pkgs, it does solve one specific purpose, to retain the existing API of a pkg (whether that's a poly-pkg or just a pkg targeting new versions of node). It also allows you to better organize your code by moving all your source code into a folder, something that was asked many times for node, but never added, but that's just a nice side effect of this proposal. We don't want to go beyond that, to suggest that everyone should have a folder (or a default folder `src/`) for their modules.

**Comment by developit** [comment]
FWIW, I've been defining `"jsnext:main"` for use with rollup and webpack, but that approach does not solve the poly-pkg usecase, so I can see the reasoning behind leaving it as a directory instead of a filepath.  It might be worth reaching out to @Rich-Harris and @sokra to see if they would be able to support `"modules.root"` in their respective build systems.

**Comment by Rich-Harris** [comment]
For my part I'm happy with whatever the community ultimately decides. Currently Rollup plans to support `.mjs` because that's what Node voted on, but if `"module"` (which is basically a standards-flavoured `"jsnext:main"`) and `"modules.root"` manage to win the community over, then we'll support that. (Strictly speaking it would be rollup-plugin-node-resolve that would need to support it; on its own Rollup only handles relative paths.)

**Comment by developit** [comment]
`.mjs` seems like an evil plot from @mjackson

**Comment by caridy** [comment]
@developit we are the original proposers of "jsnext:main" :), we can work with the different folks to accommodate the existing tools to rely on `module` entry, that should not be a problem considering that it is backward compatible.

**Comment by mjackson** [comment]
Yes, my vote is definitely for `.mjs`, but purely out of vanity 😆

**Comment by developit** [comment]
@caridy Ah - not sure how I missed that! As long as the change is for good reason (certainly seems to be) it seems worth it.  `.mjs` reminds me a bit too much of `.jsx`, which seems dangerous. All these files are JavaScript, the extension doesn't really need to provide a synopsis of the versions/features used by a given file.  I can't think of any other languages that use versioned/fragmented file extensions.
